InsightHub.Web/Controllers/AuthorsController.cs
using System.Threading.Tasks;
using InsightHub.Services.Contracts;
using InsightHub.Web.Mappers;
using InsightHub.Web.Models.AuthorsPageModels;
using Microsoft.AspNetCore.Mvc;

namespace InsightHub.Web.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IUserService userService;
        private readonly IReportService reportService;

        public AuthorsController(IUserService userService,IReportService reportService)
        {
            this.userService = userService;
            this.reportService = reportService;
        }
        // GET: Authors
        public async Task<ActionResult> Index()
        {
            var authorDtos =await this.userService.GetAuthorsForPage();
            var authorsVM = authorDtos.GetVM();

            return View(authorsVM);
        }

        // GET: Authors/Details/5
        public async Task<ActionResult> Details(AuthorReportsQueryVM reportQuery)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (reportQuery.CurrentPage == 0)
                        reportQuery.CurrentPage = 1;

                    var reports = await this.reportService.GetReportByPage(null,reportQuery.SearchCriteria,reportQuery.SearchString,null,reportQuery.CurrentPage, reportQuery.ItemsPerPage);
                    var authorInfo = await this.userService.GetAuthorInfoAsync(reportQuery.UserId);
                    reportQuery.Reports = reports.Item1.GetPageVM();
                    reportQuery.TotalPages = reports.Item2;
                    reportQuery.ImagePath = authorInfo[0];
                    reportQuery.Bio = authorInfo[1];
                    return View(reportQuery);
                }
                catch
                {
                    return NotFound();
                }
            }
            return RedirectToAction("Index", "Home");
        }


    }
}

InsightHub.Web/Controllers/UsersController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using InsightHub.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InsightHub.Web.Controllers
{
	public class UsersController : Controller
    {
        private readonly IUserService userService;

        public UsersController(IUserService userService)
        {
            this.userService = userService;
        }
        public async Task<IActionResult> CheckSubscription(string industry)
        {
            try
            {
                var isLoggedIn = User.Identity.IsAuthenticated;
                if (isLoggedIn)
                {
                    var userId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    var hasSubscription = await this.userService.IsSubscribed(userId, industry);

                    return Ok(hasSubscription);
                }

                return NotFound();
            }
            catch
            {
                return NotFound();
            }
        }
        [Authorize(Roles ="Client")]
        public async Task<IActionResult> Subscribe(string industry)
        {

            try
            {
                var isLoggedIn = User.Identity.IsAuthenticated;
                if (isLoggedIn)
                {
                    var userId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    var isSubscribed = await this.userService.Subscribe(userId, industry);

                    return Ok(isSubscribed);
                }

                return NotFound();
            }
            catch
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Client")]
        public async Task<IActionResult> Unsubscribe(string industry)
        {

            try
            {
                var isLoggedIn = User.Identity.IsAuthenticated;
                if (isLoggedIn)
                {
                    var userId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    var isUnsubbed = await this.userService.Unsubscribe(userId, industry);

                    return Ok(isUnsubbed);
                }

                return NotFound();
            }
            catch
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Client")]
        public async Task<IActionResult> Download(Guid reportId)
        {

            try
            {
                var isLoggedIn = User.Identity.IsAuthenticated;
                if (isLoggedIn)
                {
                    var userId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    var download = await this.userService.DownloadAsync(userId, reportId);

                    return Ok(download);
                }

                return NotFound();
            }
            catch
            {
                return NotFound();
            }
        }
    }
}

InsightHub.Web/Views/Shared/RegisterConfirmation.cshtml
<h1>Please wait for admin approval</h1>

InsightHub.Web/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link href="~/css/style.css" rel="stylesheet" />
	<link href="~/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/css/slick.css" rel="stylesheet" />
	<link href="~/css/theme-default.css" rel="stylesheet" />
	<link href="~/css/themify-icons.css" rel="stylesheet" />
	<link href="~/css/bootstrap-switch.css" rel="stylesheet" />
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">


</head>
<body>
	<header>
		<div class="header-area ">
			<div id="sticky-header" class="main-header-area details_nav">
				<div class="container">
					<div class="header_bottom_border">
						<div class="row align-items-center">
							<div class="col-xl-3 col-lg-2">
								<div class="logo navbar-brand">
									<a id="mainlogo" asp-area="" asp-controller="Home" asp-action="Index">
										InsightHub.
									</a>
								</div>
							</div>
							<div class="col-xl-6 col-lg-7">
								<div class="main-menu  d-none d-lg-block">
									<nav>
										<ul id="navigation">
											<li>
												<a asp-area="" asp-controller="Reports" asp-action="Index"
												   asp-route-currentPage="1">reports <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="information technology"
                                                           asp-route-currentPage="1">IT</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="healthcare"
                                                           asp-route-currentPage="1">Healthcare</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="energy"
                                                           asp-route-currentPage="1">Energy</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="finance"
                                                           asp-route-currentPage="1">Finance</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="marketing"
                                                           asp-route-currentPage="1">Marketing</a>
                                                    </li>
                                                </ul>
											</li>
											<li><a asp-area="" asp-controller="Authors" asp-action="Index">Authors</a></li>
											<li><a asp-area="" asp-controller="Home" asp-action="About">About us</a></li>
											@if (User.IsInRole("Admin"))
											{
												<li>
													<a href="#">Admin panel <i class="ti-angle-down"></i></a>
													<ul class="submenu">
														<li><a asp-area="Admin" asp-controller="Users" asp-action="Authors">Authors</a></li>
														<li><a asp-area="Admin" asp-controller="Users" asp-action="Clients">Clients</a></li>
														<li><a asp-area="Admin" asp-controller="Users" asp-action="Pending" id="pending">Pending</a></li>
													</ul>
												</li>
											}
										</ul>
									</nav>
								</div>
							</div>
							<div class="col-xl-3 col-lg-3 d-none d-lg-block">
								<div class="Appointment">
									<div class="book_btn d-none d-flex justify-content-between">
										@if (User.IsInRole("Author"))
										{
											<a asp-area="Author" asp-controller="Reports" asp-action="Create" class="manageprofilebtn createbtn">
												<img src="~/img/svg_icon/pdf (1).png" />
											</a>
										}
										@if (!User.Identity.IsAuthenticated)
										{
											<a asp-area="Identity" asp-page="/Account/Login" class="manageprofilebtn">Login</a>
											<a asp-area="Identity" asp-page="/Account/Register" class="manageprofilebtn">Register</a>
										}
										else
										{
											if (!User.IsInRole("Admin"))
											{
												<a asp-area="Identity" asp-page="/Account/Manage/Reports" title="Manage" class="manageprofilebtn">Profile</a>
											}
											else
											{
												<a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" class="manageprofilebtn">Profile</a>

											}
											<form id="form1" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
												<a href="#" onclick="document.getElementById('form1').submit();">Logout</a>
											</form>

										}
									</div>
								</div>
							</div>
							<div class="col-12">
								<div class="mobile_menu d-block d-lg-none"></div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</header>
    <div class="page-container">

        <div class="content-wrap">
            @RenderBody()
            <!-- footer start -->
        </div>
        <footer class="footer">

            <div class="copy-right_text">
                <div class="container">
                    <div class="footer_border"></div>
                    <div class="row">
                        <div class="col-xl-12">
                            <p class="copy_right text-center">
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved |  Team 10  by <a href="https://gitlab.com/dimitar_grozev">Mitko</a> & <a href="https://gitlab.com/mdotgeorgieva">Mimi</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--/ footer end  -->
        <!-- JS here -->
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap-switch.js"></script>
        <script src="~/js/Notifications.js"></script>
        @RenderSection("Scripts", required: false)
        @await Component.InvokeAsync("NToastNotify")
    </div>
</body>
</html>

InsightHub.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]InsightHub</title>
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/slick.css" rel="stylesheet" />
    <link href="~/css/theme-default.css" rel="stylesheet" />
    <link href="~/css/bootstrap-switch.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/fontawesome.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div id="logo" class="navbar-brand">
                                    <a id="mainlogo" asp-controller="Home" asp-action="Index">
                                        InsightHub.
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-5 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li>
                                                <a asp-area="" asp-controller="Reports" asp-action="Index"
														   asp-route-currentPage= "1">reports <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="information technology"
                                                           asp-route-currentPage="1">IT</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="healthcare"
                                                           asp-route-currentPage="1">Healthcare</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="energy"
                                                           asp-route-currentPage="1">Energy</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="finance"
                                                           asp-route-currentPage="1">Finance</a>
                                                    </li>
                                                    <li>
                                                        <a asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry="marketing"
                                                           asp-route-currentPage="1">Marketing</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li><a asp-controller="Authors" asp-action="Index">Authors</a></li>
                                            <li><a asp-controller="Home" asp-action="About">About us</a></li>
                                            @if (User.IsInRole("Admin"))
                                            {
                                                <li>
                                                    <a href="#">Admin panel <i class="ti-angle-down"></i></a>
                                                    <ul class="submenu">
                                                        <li><a asp-area="Admin" asp-controller="Users" asp-action="Authors">Authors</a></li>
                                                        <li><a asp-area="Admin" asp-controller="Users" asp-action="Clients">Clients</a></li>
                                                        <li><a asp-area="Admin" asp-controller="Users" asp-action="Pending" id="pending">Pending</a></li>
                                                    </ul>
                                                </li>
                                            }
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                   
                                    <div class="book_btn d-none d-flex justify-content-between">
                                        @if (User.IsInRole("Author"))
										{
                                            <a asp-area="Author" asp-controller="Reports" asp-action="Create" class="manageprofilebtn createbtn">
                                                <img src="~/img/svg_icon/pdf (1).png" />
                                            </a>
										}
                                        @if (!User.Identity.IsAuthenticated)
                                        {
                                            <a asp-area="Identity" asp-page="/Account/Login" class="manageprofilebtn">Login</a>
                                            <a asp-area="Identity" asp-page="/Account/Register" class="manageprofilebtn">Register</a>
                                        }   
                                        else
                                        {
                                            if (!User.IsInRole("Admin"))
                                            {
                                                <a asp-area="Identity" asp-page="/Account/Manage/Reports" title="Manage" class="manageprofilebtn">Profile</a>
                                            }
                                            else
                                            {
                                                <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" class="manageprofilebtn">Profile</a>

                                            }

                                            <form id="form1" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                                <a href="#" onclick="document.getElementById('form1').submit();">Logout</a>
                                            </form>

                                        }
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <div class="page-container">
        <div class="content-wrap">
            @RenderBody()
        </div>

        <footer class="footer">
            <div class="copy-right_text">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <p class="copy_right text-center">
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved |  Team 10  by <a href="https://gitlab.com/dimitar_grozev">Mitko</a> & <a href="https://gitlab.com/mdotgeorgieva">Mimi</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- JS here -->
        <script src="~/js/jquery.slicknav.min.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/bootstrap-switch.js"></script>
        <script src="~/js/Notifications.js"></script>
        @RenderSection("Scripts", required: false)
        @await Component.InvokeAsync("NToastNotify")
    </div>
</body>
</html>