InsightHub.Web/Areas/Author/Models/CreateReportVM.cs
using System;
using System.ComponentModel;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace InsightHub.Web.Areas.Author.Models
{
	public class CreateReportVM
    {
		[DisplayName("Title")]
		[Required]
		[StringLength(150, ErrorMessage = "{0} must be between {2} and {1} characters", MinimumLength = 10)]
		public string Name { get; set; }
		[DisplayName("Industry")]
		[Required]
		public Guid IndustryId { get; set; }
		[DisplayName("Short summary")]
		[Required]
		[MinLength(500, ErrorMessage = "{0} must be at least {1} characters long")]
		public string Summary { get; set; }
		[Required]
		public IFormFile Content { get; set; }
		[DisplayName("Tags (max. 3)")]
		public string Tags { get; set; }
		public IFormFile ImagePath { get; set; }
	}
}

InsightHub.Web/Areas/Author/Models/DeleteReportVM.cs
using System;

namespace InsightHub.Web.Areas.Author.Models
{
	public class DeleteReportVM
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
}

InsightHub.Web/Areas/Author/Models/UpdateReportVM.cs
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace InsightHub.Web.Areas.Author.Models
{
	public class UpdateReportVM
    {
        [Required]
        public Guid Id { get; set; }
        [Required]
        [StringLength(150, ErrorMessage = "{0} must be between {2} and {1} characters", MinimumLength = 10)]
        [DisplayName("Title")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Industry")]
        public Guid IndustryId { get; set; }
        [Required]
        [MinLength(500, ErrorMessage = "{0} must be between at least {1} characters long")]
        public string Summary { get; set; }
        [DisplayName("Tags (max. 3)")]
        public string Tags { get; set; }
        public IFormFile Content { get; set; }
        public IFormFile Photo { get; set; }
    }
}

InsightHub.Web/Areas/Author/Controllers/ReportsController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using InsightHub.Services.Contracts;
using InsightHub.Web.Areas.Author.Models;
using InsightHub.Web.Mappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;

namespace InsightHub.Web.Areas.Author.Controllers
{
    [Area("Author")]
    [Authorize(Roles = "Author, Admin")]

    public class ReportsController : Controller
    {
        private readonly IReportService reportService;
        private readonly IIndustryService industryService;
        private readonly IBlobService blobService;
        private readonly IPhotoService photoService;
        private readonly IToastNotification toastNotification;

        public ReportsController(IReportService reportService, IIndustryService industryService, 
                                 IBlobService blobService, IPhotoService photoService,IToastNotification toastNotification)
        {
            this.reportService = reportService;
            this.industryService = industryService;
            this.blobService = blobService;
            this.photoService = photoService;
            this.toastNotification = toastNotification;
        }


        // GET: Reports/Create
        public async Task<ActionResult> Create()
        {
            try
            {
                ViewData["IndustryId"] = new SelectList(await this.industryService.GetAsync(), "Id", "Name");

                return View();
            }
            catch
            {
                this.toastNotification.AddWarningToastMessage("Something went wrong! Count not create report!");
                return RedirectToAction("Index", "Home", new { area = ""});

            }
        }

        // POST: Reports/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateReportVM report)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var reportDto = report.GetDto();
                    reportDto.AuthorId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    //TODO Private method for userID
                    var newReport = await this.reportService.CreateAsync(reportDto);



                    await this.blobService.UploadFileBlobAsync(newReport.Id.ToString(), report.Content);
                    if(report.ImagePath != null)
                    {
                        await this.photoService.UploadPhoto(report.ImagePath, newReport.ImagePath);
                    }

                    this.toastNotification.AddInfoToastMessage($"{report.Name} was successfully created. Please for admin approval!");
                    return RedirectToAction("Index", "Home", new { area = ""});
                }
                catch
                {
                    this.toastNotification.AddWarningToastMessage("Something went wrong! Count not create report!");
                    return RedirectToAction("Create", "Reports");
                }
            }

            return RedirectToAction("Create", "Reports");
        }

        // GET: Reports/Edit/5
        public async Task<ActionResult> Edit(Guid reportId)
        {
            try
            {
                ViewData["IndustryId"] = new SelectList(await this.industryService.GetAsync(), "Id", "Name");

                var report = await this.reportService.GetAsync(reportId);
                var reportVm = report.GetUpdateVM();
                return View(reportVm);
            }
            catch
            {
                this.toastNotification.AddWarningToastMessage("Something went wrong! Count not edit report!");
                return RedirectToAction("Index", "Home", new { area = "" });
            }
        }

        // POST: Reports/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UpdateReportVM report, string url)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var reportDto = report.GetDTO();
                    var newReport = await this.reportService.UpdateAsync(reportDto);
                    if(report.Content != null)
                    {
                        await this.blobService.DeleteBlob(report.Id.ToString());
                        await this.blobService.UploadFileBlobAsync(newReport.Id.ToString(), report.Content);
                    }
                    if (report.Photo != null)
                    {
                        await this.photoService.UploadPhoto(report.Photo, newReport.ImagePath);
                    }

                    if (url == "author")
                        return RedirectToPage("/Account/Manage/Reports", new { area = "Identity" });

                    return RedirectToAction("Index", "Reports", new { area = "" });
                }
                catch
                {
                    this.toastNotification.AddWarningToastMessage("Something went wrong! Count not edit report!");
                    return RedirectToAction("Edit", "Reports");
                }
            }
            return RedirectToAction("Edit", "Reports");
        }

        public async Task<ActionResult> Delete(Guid reportId, string url)
        {
            try
            {
                await this.reportService.DeleteAsync(reportId);
                await this.blobService.DeleteBlob(reportId.ToString());

                if (url == "author")
                    return RedirectToPage("/Account/Manage/Reports", new { area = "Identity" });

                return RedirectToAction("Index", "Reports", new { area = "" });
            }
            catch
            {
                this.toastNotification.AddWarningToastMessage("Something went wrong! Count not delete report!");

                return View();
            }
        }
    }
}

InsightHub.Web/Controllers/AuthorsController.cs
using System.Threading.Tasks;
using InsightHub.Services.Contracts;
using InsightHub.Web.Mappers;
using InsightHub.Web.Models.AuthorsPageModels;
using Microsoft.AspNetCore.Mvc;

namespace InsightHub.Web.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IUserService userService;
        private readonly IReportService reportService;

        public AuthorsController(IUserService userService,IReportService reportService)
        {
            this.userService = userService;
            this.reportService = reportService;
        }
        // GET: Authors
        public async Task<ActionResult> Index()
        {
            var authorDtos =await this.userService.GetAuthorsForPage();
            var authorsVM = authorDtos.GetVM();

            return View(authorsVM);
        }

        // GET: Authors/Details/5
        public async Task<ActionResult> Details(AuthorReportsQueryVM reportQuery)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (reportQuery.CurrentPage == 0)
                        reportQuery.CurrentPage = 1;

                    var reports = await this.reportService.GetReportByPage(null,reportQuery.SearchCriteria,reportQuery.SearchString,null,reportQuery.CurrentPage, reportQuery.ItemsPerPage);
                    var authorInfo = await this.userService.GetAuthorInfoAsync(reportQuery.UserId);
                    reportQuery.Reports = reports.Item1.GetPageVM();
                    reportQuery.TotalPages = reports.Item2;
                    reportQuery.ImagePath = authorInfo[0];
                    reportQuery.Bio = authorInfo[1];
                    return View(reportQuery);
                }
                catch
                {
                    return NotFound();
                }
            }
            return RedirectToAction("Index", "Home");
        }


    }
}

InsightHub.Web/Controllers/BlobsController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Azure;
using InsightHub.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InsightHub.Web.Controllers
{
    public class BlobsController : Controller
    {
        private readonly IBlobService blobService;
        private readonly IUserService userService;

        public BlobsController(IBlobService blobService, IUserService userService)
        {
            this.blobService = blobService;
            this.userService = userService;
        }

        [HttpGet]
        [Authorize(Roles = "Client, Admin, Author")]
        public async Task<IActionResult> GetBlob(string reportId)
        {
            try
            {
                var data = await this.blobService.GetBlobAsync(reportId);

                var isLoggedIn = User.Identity.IsAuthenticated;
                if (isLoggedIn && User.IsInRole("Client"))
                {
                    var userId = Guid.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                    await this.userService.DownloadAsync(userId, Guid.Parse(reportId));
                }

                return File(data.Content, data.ContentType);
            }
            catch (RequestFailedException)
            {
                return Unauthorized();
            }
            catch
            {
                return NotFound();
            }
        }

        //[HttpPost]

        //public async Task<IActionResult> UploadFile([FromBody] UploadFileRequest request)
        //{
        //    await this.blobService.UploadFileBlobAsync(request);

        //    return Ok();
        //}

        [HttpDelete]
        public async Task<IActionResult> DeleteBlob(string id)
        {
            try
            {
                await this.blobService.DeleteBlob(id);

                return Ok();
            }
            catch
            {
                return NotFound();
            }
        }
    }
}

InsightHub.Web/Views/Authors/Details.cshtml
@model AuthorReportsQueryVM
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";
}

    <head>
        <link href="~/css/report-page.css" rel="stylesheet" />
        <link href="~/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/css/AuthorPersonalPage.css" rel="stylesheet" />
        <title>InsightHub | @Model.SearchString</title>

    </head>

<body>
    <div class="author-info-holder">
        <div class="container">
            <div class="row">
                <div class="col-12 d-inline-flex">
                    <div class="col-2">
                        <div class="image-container">
                            <div class="author-picture" style="background-image: url('/img/team/@Model.ImagePath');">
                                @*<img src="@Model.ImagePath" />*@
                            </div>
                        </div>
                    </div>
                    <div class="col-10">
                        <div class="author-info">
                            <div class="author-name">
                                <p> @Model.SearchString </p>
                            </div>
                            <div class="author-bio">
                                @Model.Bio
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="rp-main">

        <div class="container">
            <div class="row">
                @foreach (var report in Model.Reports)
                {
                    <div class="d-flex col-12 rp-card">
                        <div class="col-4 rp-img-container">
                            <div class="rp-img" style="background-image:url('../img/reports/@report.ImagePath');">
                            </div>
                        </div>
                        <div class="d-flex flex-column col-6">
                            <p class="rp-title"><a asp-controller="Reports" asp-action="Details" asp-route-reportId="@report.Id">@report.Name</a></p>
                            <div class="pb-2">
                                @foreach (var tag in report.Tags)
                                {
                                    <a asp-controller="Reports" asp-action="Index" asp-route-searchCriteria="tag"
                                       asp-route-searchString="@tag" asp-route-currentPage="1" class="rp-tags">@tag</a>
                                }
                            </div>
                            <q class="rp-quote">@report.Description</q> <br>
                            <div class="test d-flex">
                                <a class="rp-author" asp-action="Details" asp-route-searchString="@Model.SearchString" asp-route-currentPage="1" asp-route-userId="@Model.UserId">@report.Author</a>
                                <p class="rp-downloads">Downloaded @report.Downloads times.</p>
                            </div>
                        </div>
                        <div class="rp-button-holder d-flex flex-column col-2">
                            <a asp-controller="Reports" asp-action="Details" asp-route-reportId="@report.Id" class="btn genric-btn circle rp-button rp-button-details">Read more</a>

                            @if (!User.IsInRole("Author") && !User.IsInRole("Admin"))
                            {
                                <a asp-controller="Blobs" asp-action="GetBlob" asp-route-reportId="@report.Id" target="_blank"
                                   class="btn genric-btn circle rp-button rp-button-download">Download</a>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-area="Admin" asp-controller="Reports" asp-action="UpdateReport" asp-route-id="@report.Id"
                                   class="btn genric-btn circle rp-button rp-button-update">Update</a>
                                <a asp-area="Admin" asp-controller="Reports" asp-action="FeatureReport" asp-route-id="@report.Id"
                                   class="btn genric-btn circle rp-button rp-button-feature">Feature</a>
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="rp-pagination">
            @if (Model.CurrentPage != 1)
            {
                <a asp-route-currentPage=@(Model.CurrentPage - 1)
                   asp-action="Details" asp-route-searchString="@Model.SearchString" asp-route-userId="@Model.UserId"
                   class="btn genric-btn circle">Previous</a>
            }

            @if ((Model.TotalPages - Model.CurrentPage) > 0)
            {
                <a asp-route-currentPage=@(Model.CurrentPage + 1)
                   asp-action="Details" asp-route-searchString="@Model.SearchString" asp-route-userId="@Model.UserId"
                   class="btn genric-btn circle">Next</a>
            }

        </div>

    </section>
    <!--main area ends-->
    <!--footer area starts-->
    <footer class="footer">
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved |  Team 10  by <a href="https://gitlab.com/dimitar_grozev">Mitko</a> & <a href="https://gitlab.com/mdotgeorgieva">Mimi</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!--footer area ends-->
</body>
<script src="~/js/vendor/jquery-1.12.4.min.js"></script>
<script src="~/js/truncate-text.js"></script>

InsightHub.Web/Views/Authors/Index.cshtml
@{
    Layout = "_EmptyLayout";
}
@model ICollection<AuthorVM>
<!doctype html>
<head>
    <link href="~/css/AuthorsPage.css" rel="stylesheet" />

</head>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>InsightHub | Authors</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
    <!-- header-start -->
    <!-- header-end -->
            <div class="service_area">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="section_title text-center mb-50">
                                <h3>Our Authors</h3>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        @foreach (var author in Model)
                        {

                            <div class="col-xl-4 col-md-6 col-lg-4">
                                <div class="single_service text-center">
                                    <div class="authors" style="background-image: url('/img/team/@author.ImagePath');">
                                    </div>
                                    <h3>@author.Fullname</h3>

                                    <div class="description">
                                        <p class="text">@author.Bio</p>
                                        <span class="tooltiptext">@author.Bio</span>
                                    </div>
                                    <a asp-controller="Authors" asp-action="Details" asp-route-searchString="@author.Fullname" asp-route-currentPage="1" asp-route-userId="@author.Id">Reports</a>

                                </div>
                            </div>
                        }


                    </div>
                </div>
            </div>

        <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
        <script src="~/js/truncate1-text1.js"></script>
</body>

</html>